# -*- coding: utf-8 -*-
"""TaskA_Bsce23042.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZdBBUW_5AT85QqKVvo9HNv5F475aUDh
"""

# PART A — PLANT DISEASE CLASSIFICATION

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import kagglehub

from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)

from sklearn.metrics import (
    confusion_matrix,
    classification_report
)


ROLL_NO = 42

random.seed(ROLL_NO)
np.random.seed(ROLL_NO)
tf.random.set_seed(ROLL_NO)

print("TensorFlow Version:", tf.__version__)
print(f"Project Running for Roll No: {ROLL_NO}")



# DOWNLOAD DATASET

path = kagglehub.dataset_download(
    "mohitsingh1804/plantvillage"
)

print(" Dataset Downloaded")
print("Dataset Path:", path)



# FIND DATASET PATH

for root, dirs, files in os.walk(path):

    if 'train' in dirs and 'val' in dirs:

        DATASET_PATH = root
        break

print(" Correct Dataset Path Found")
print(DATASET_PATH)

TRAIN_DIR = os.path.join(DATASET_PATH, 'train')
VAL_DIR   = os.path.join(DATASET_PATH, 'val')

print("Train Directory:", TRAIN_DIR)
print("Validation Directory:", VAL_DIR)



# LOAD DATASET

IMG_SIZE = (128, 128)
BATCH_SIZE = 32

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    TRAIN_DIR,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    VAL_DIR,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

class_names = train_ds.class_names
num_classes = len(class_names)

print("\n Total Classes:", num_classes)

for i, cls in enumerate(class_names):
    print(f"{i+1}. {cls}")



# DATASET INFORMATION

train_count = 0
val_count = 0

for images, labels in train_ds:
    train_count += images.shape[0]

for images, labels in val_ds:
    val_count += images.shape[0]

print(f"\nTraining Images : {train_count}")
print(f"Validation Images: {val_count}")



# VISUALIZE DATASET

plt.figure(figsize=(12,12))

for images, labels in train_ds.take(1):

    for i in range(9):

        ax = plt.subplot(3,3,i+1)

        plt.imshow(images[i].numpy().astype("uint8"))

        plt.title(class_names[labels[i]])

        plt.axis("off")

plt.tight_layout()
plt.show()



# CLASS DISTRIBUTION

class_counts = {}

for cls in class_names:

    cls_path = os.path.join(TRAIN_DIR, cls)

    count = len([
        f for f in os.listdir(cls_path)
        if f.lower().endswith(('.jpg','.jpeg','.png'))
    ])

    class_counts[cls] = count

plt.figure(figsize=(18,5))

plt.bar(
    range(num_classes),
    class_counts.values(),
    color='steelblue'
)

plt.xticks(
    range(num_classes),
    [c.replace('___','\n') for c in class_names],
    rotation=90,
    fontsize=7
)

plt.title(f"Class Distribution | Roll No {ROLL_NO}",
          fontweight='bold')

plt.ylabel("Number of Images")

plt.tight_layout()

plt.savefig(
    f"class_distribution_{ROLL_NO}.png",
    dpi=150,
    bbox_inches='tight'
)

plt.show()



# PREFETCH DATASET

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds   = val_ds.prefetch(buffer_size=AUTOTUNE)

print(" Dataset Optimized")



# BUILD CNN MODEL

model = Sequential([

    layers.Rescaling(1./255,
                     input_shape=(128,128,3)),

    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(),

    # PERSONALIZED DROPOUT
    layers.Dropout(0.35),

    layers.Flatten(),

    layers.Dense(128, activation='relu'),

    layers.Dropout(0.3),

    layers.Dense(num_classes, activation='softmax')

])

# PERSONALIZED MODEL NAME
model._name = f"PlantDiseaseCNN_Roll{ROLL_NO}"

model.summary()


# COMPILE MODEL

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print(" Model Compiled")



# CALLBACKS

callbacks = [

    EarlyStopping(
        monitor='val_loss',
        patience=3,
        restore_best_weights=True,
        verbose=1
    ),

    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=2,
        verbose=1
    ),

    ModelCheckpoint(
        f'best_plant_model_{ROLL_NO}.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]



# TRAIN MODEL

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=callbacks
)

print(" Training Complete")



# ACCURACY & LOSS GRAPHS

epochs_range = range(
    1,
    len(history.history['accuracy']) + 1
)

fig, axes = plt.subplots(1,2,figsize=(14,5))

# Accuracy
axes[0].plot(
    epochs_range,
    history.history['accuracy'],
    'b-o',
    label='Train'
)

axes[0].plot(
    epochs_range,
    history.history['val_accuracy'],
    'r-o',
    label='Validation'
)

axes[0].set_title("Accuracy")
axes[0].legend()
axes[0].grid(alpha=0.3)

# Loss
axes[1].plot(
    epochs_range,
    history.history['loss'],
    'b-o',
    label='Train'
)

axes[1].plot(
    epochs_range,
    history.history['val_loss'],
    'r-o',
    label='Validation'
)

axes[1].set_title("Loss")
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.tight_layout()

plt.savefig(
    f"plant_training_curves_{ROLL_NO}.png",
    dpi=150,
    bbox_inches='tight'
)

plt.show()


# EVALUATE MODEL

loss, accuracy = model.evaluate(val_ds)

print(f"\n Validation Accuracy: {accuracy:.4f}")
print(f" Validation Loss    : {loss:.4f}")



# GENERATE PREDICTIONS

y_true = []
y_pred = []

for images, labels in val_ds:

    preds = model.predict(images, verbose=0)

    preds = np.argmax(preds, axis=1)

    y_true.extend(labels.numpy())
    y_pred.extend(preds)

y_true = np.array(y_true)
y_pred = np.array(y_pred)

print(" Predictions Generated")



# CONFUSION MATRIX

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(12,10))

sns.heatmap(
    cm,
    cmap='Blues',
    annot=False
)

plt.title(f"Confusion Matrix | Roll No {ROLL_NO}")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.tight_layout()

plt.savefig(
    f"plant_confusion_matrix_{ROLL_NO}.png",
    dpi=150,
    bbox_inches='tight'
)

plt.show()



# CLASSIFICATION REPORT

report = classification_report(
    y_true,
    y_pred,
    target_names=class_names
)

print(report)



# SAMPLE PREDICTIONS

plt.figure(figsize=(14,14))

for images, labels in val_ds.take(1):

    preds = model.predict(images, verbose=0)
    preds = np.argmax(preds, axis=1)

    for i in range(9):

        ax = plt.subplot(3,3,i+1)

        plt.imshow(images[i].numpy().astype("uint8"))

        true_label = class_names[labels[i]]
        pred_label = class_names[preds[i]]

        plt.title(
            f"True: {true_label}\nPred: {pred_label}",
            fontsize=8
        )

        plt.axis("off")

plt.tight_layout()
plt.show()


# =========================================================
# FINAL RESULTS SUMMARY
# =========================================================
best_epoch = np.argmax(
    history.history['val_accuracy']
) + 1

best_acc = max(
    history.history['val_accuracy']
)

print("\n===================================")
print("PART A — FINAL RESULTS")
print("===================================")

print(f"Roll Number             : {ROLL_NO}")
print(f"Number of Classes       : {num_classes}")
print(f"Training Images         : {train_count}")
print(f"Validation Images       : {val_count}")

print(f"\nBest Validation Accuracy : {best_acc:.4f}")
print(f"Best Epoch               : {best_epoch}")

print("\n PART A COMPLETE")